# Generated by Django 5.0 on 2023-12-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
