# Generated by Django 5.0 on 2023-12-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_video_class_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
    ]
