# Generated by Django 5.0 on 2023-12-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_remove_course_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='assignment',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
        migrations.AddField(
            model_name='video',
            name='quiz',
            field=models.URLField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='class_file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
