# Generated by Django 5.0 on 2023-12-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_video_assignment_video_quiz_alter_video_class_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='quiz',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
