# Generated by Django 4.2.7 on 2024-01-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default=0, upload_to='Teams_members/'),
            preserve_default=False,
        ),
    ]
