# Generated by Django 4.2.7 on 2024-01-16 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_enrollment_video_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='video_completion',
        ),
    ]
