# Generated by Django 4.2.7 on 2024-01-16 11:15

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_remove_enrollment_video_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_files',
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to=lms.models.UploadToPath('course_videos/')),
        ),
    ]
