# Generated by Django 4.2.7 on 2024-01-17 19:47

from django.db import migrations, models
import lms.models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_remove_course_course_files_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='banner',
            field=models.ImageField(upload_to=lms.models.UploadToPath('courses_banner/')),
        ),
    ]
